language: c
install:
  - sudo apt-get install bc
  - git clone git://github.com/fish-shell/fish-shell.git
  - cd fish-shell
  - autoconf && ./configure && make && sudo make install
  - cd -
  - git clone git://github.com/terlar/fish-tank.git
  - cd fish-tank
  - sudo make install
  - cd -

script: make test
